name: compiler-build

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-2019,macos-10.15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.9.0

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        if: runner.os != 'Linux'
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -G Ninja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --config $BUILD_TYPE

      - name: Install
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix ../install
