name: compiler-build

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-2019,macos-10.15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.9.0

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DRCVM_TEST=ON

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        shell: bash
        working-directory: ${{github.workspace}}/build/test
        run: ctest -C $BUILD_TYPE

      - name: WinLog
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}/build/test/Testing/Temporary
        run: cat LastTest.log